<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Channel_model extends CI_Model {
   
   function __construct(){
        parent::__construct();

        $dbDaPros = $this->load->database('default', TRUE);
        $dbProfiling = $this->load->database('profiling', TRUE);
   }	
	
   public function getDataProfiling(){
        $dbProfiling = $this->load->database('profiling', TRUE);

        return $dbProfiling->get('profiling')->result_array();
     }

   public function getDataPros(){
        $dbPros = $this->load->database('default', TRUE);

        return $dbPros->get('data_lead')->result_array();
    }

    public function updateOpsiCall($noSpeedy, $Channel){
        $dbPros = $this->load->database('default', TRUE);
        
        $data = array(
            'channel' => $Channel
        );

        $queryUpdateChannel = $dbPros->where('no_speedy', $noSpeedy)->update('data_lead', $data);

        return $queryUpdateChannel;
    }

};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-01-31 15:28:46 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
